repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua-system
        args: [--config-path, .stylua.toml]
  - repo: local
    hooks:
      - id: ghostty-validate-config
        name: ghostty validate config
        entry: ghostty +validate-config --config-file=ghostty/.config/ghostty/config
        language: system
        files: ^ghostty/.config/ghostty/config$
        pass_filenames: false
      - id: bash-syntax
        name: bash syntax check
        entry: bash -n
        language: system
        types: [shell]
      - id: shfmt
        name: shfmt
        entry: shfmt -d -i 4
        language: system
        types: [shell]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ^(_archive/|bash/\.bash(_profile|rc)$|direnv/\.config/direnv/direnvrc$)
      - id: shellcheck-bash-config
        name: shellcheck Bash configuration
        entry: shellcheck --shell=bash --exclude=SC1090 --exclude=SC1091
        language: system
        files: ^(bash/\.bash(_profile|rc)$|direnv/\.config/direnv/direnvrc)$
