%hidden DARK0=#282828     # Main dark background
%hidden LIGHT0=#ebdbb2    # Main light foreground
%hidden LIGHT1=#fbf1c7    # Bright foreground
%hidden PURPLE=#d3869b
%hidden ORANGE=#fe8019
%hidden YELLOW=#fabd2f
%hidden GREEN=#b8bb26
%hidden BLUE=#83a598
%hidden AQUA=#8ec07c
%hidden RED=#fb4934

%hidden FG=$PURPLE
%hidden BG=$DARK0
%hidden FG_BORDER=colour238

set-option -g display-panes-active-colour "$FG"
set-option -g display-panes-colour "$FG"
set-option -g message-style "fg=$FG,bg=$BG"
set-option -g pane-active-border-style "fg=$FG_BORDER"
set-option -g pane-border-style "fg=$FG_BORDER"
set-option -g status-style "fg=$FG,bg=$BG"
set-window-option -g clock-mode-colour "$FG"
set-window-option -g mode-style "fg=$FG,bg=$BG"
set-window-option -g window-status-bell-style "fg=$FG,bg=$BG"
set-window-option -g window-status-current-style "fg=$BG,bg=$FG,bold"
set-window-option -g window-status-style "fg=$FG,bg=$BG"
